const fs=require('fs'),path=require('path'),{execSync}=require('child_process');
fs.writeFileSync('backend'+path.sep+'package.json',"{\n  \"name\": \"dropos-backend\",\n  \"version\": \"1.0.0\",\n  \"description\": \"DropOS SaaS Dropshipping Platform \\u2014 Backend API\",\n  \"main\": \"dist/server.js\",\n  \"scripts\": {\n    \"dev\": \"ts-node-dev --respawn --transpile-only src/server.ts\",\n    \"build\": \"npx tsc --skipLibCheck\",\n    \"start\": \"node --max-old-space-size=400 dist/server.js\",\n    \"seed\": \"npx ts-node prisma/seed.ts\",\n    \"generate\": \"npx prisma generate\",\n    \"migrate\": \"npx prisma migrate dev\",\n    \"studio\": \"npx prisma studio\"\n  },\n  \"dependencies\": {\n    \"@prisma/client\": \"^5.7.0\",\n    \"@types/node\": \"^20.10.0\",\n    \"axios\": \"^1.6.2\",\n    \"bcryptjs\": \"^2.4.3\",\n    \"cloudinary\": \"^2.0.0\",\n    \"compression\": \"^1.7.4\",\n    \"cookie-parser\": \"^1.4.6\",\n    \"cors\": \"^2.8.5\",\n    \"dotenv\": \"^16.3.1\",\n    \"express\": \"^4.18.2\",\n    \"express-async-errors\": \"^3.1.1\",\n    \"express-rate-limit\": \"^7.1.5\",\n    \"express-validator\": \"^7.0.1\",\n    \"helmet\": \"^7.1.0\",\n    \"jsonwebtoken\": \"^9.0.2\",\n    \"morgan\": \"^1.10.0\",\n    \"multer\": \"^1.4.5-lts.1\",\n    \"node-fetch\": \"^2.7.0\",\n    \"nodemailer\": \"^6.9.7\",\n    \"prisma\": \"^5.7.0\",\n    \"qrcode\": \"^1.5.3\",\n    \"resend\": \"^6.10.0\",\n    \"speakeasy\": \"^2.0.0\",\n    \"stripe\": \"^14.9.0\",\n    \"ts-node\": \"^10.9.1\",\n    \"twilio\": \"^4.19.0\",\n    \"typescript\": \"^5.3.2\",\n    \"uuid\": \"^9.0.1\",\n    \"web-push\": \"^3.6.7\",\n    \"winston\": \"^3.11.0\",\n    \"zod\": \"^3.22.4\"\n  },\n  \"devDependencies\": {\n    \"@types/bcryptjs\": \"^2.4.6\",\n    \"@types/compression\": \"^1.7.5\",\n    \"@types/cookie-parser\": \"^1.4.6\",\n    \"@types/cors\": \"^2.8.17\",\n    \"@types/express\": \"^4.17.21\",\n    \"@types/jsonwebtoken\": \"^9.0.5\",\n    \"@types/morgan\": \"^1.9.9\",\n    \"@types/multer\": \"^1.4.11\",\n    \"@types/node-fetch\": \"^2.6.11\",\n    \"@types/nodemailer\": \"^6.4.14\",\n    \"@types/qrcode\": \"^1.5.5\",\n    \"@types/speakeasy\": \"^2.0.8\",\n    \"@types/twilio\": \"^3.19.3\",\n    \"@types/uuid\": \"^9.0.7\",\n    \"@types/web-push\": \"^3.6.3\",\n    \"ts-node-dev\": \"^2.0.0\"\n  }\n}",'utf8');
console.log('OK package.json');
try{
  execSync('git add .',{stdio:'inherit'});
  const st=execSync('git status --short',{encoding:'utf8'}).trim();
  if(st){
    execSync('git commit -m "fix: compile TS to dist on build, run node dist/server.js to fix OOM on Render Starter"',{stdio:'inherit'});
    execSync('git push origin main',{stdio:'inherit'});
    console.log('Pushed.');
  }else{console.log('Nothing to commit');}
}catch(e){console.log('Git:',e.message);}
