const fs=require('fs'),path=require('path'),{execSync}=require('child_process');
const files={"backend/src/routes/loyalty.routes.ts":"// ============================================================\n// Loyalty Points — Routes + Controller\n// Path: backend/src/routes/loyalty.routes.ts\n// Add to app.ts: app.use(\"/api/loyalty\", loyaltyRoutes);\n// ============================================================\nimport prisma from \"../lib/prisma\";\nimport { Router, Request, Response } from \"express\";\nimport { authenticate }       from \"../middleware/auth\";\nimport { awardPoints, redeemPoints, getLoyaltyStatus } from \"../services/loyalty.service\";\n\nconst router = Router();\nrouter.use(authenticate);\n\n// GET /api/loyalty/status?customerId=X&storeId=Y\nrouter.get(\"/:storeId/stats\",  async (req: Request, res: Response) => {\n  const { storeId } = req.params;\n  const accounts = await prisma.loyaltyAccount.findMany({ where: { storeId } as any, take: 10 }).catch(()=>[]);\n  const points = (accounts as any[]).reduce((a: number, acc: any) => a + (acc.points || 0), 0);\n  const tiers = [\n    { name:\"Bronze\", min:0,    max:999,  members:0, color:\"#CD7F32\", perks:[\"5% discount\",\"Birthday bonus\"] },\n    { name:\"Silver\", min:1000, max:4999, members:0, color:\"#C0C0C0\", perks:[\"10% discount\",\"Free shipping\",\"Priority support\"] },\n    { name:\"Gold\",   min:5000, max:null, members:0, color:\"#FFD700\", perks:[\"15% discount\",\"Free shipping\",\"Dedicated support\",\"Exclusive products\"] },\n  ];\n  res.json({ success:true, data:{ totalMembers:accounts.length, totalPoints:points, tiers, recentActivity:[] }});\n});\nrouter.put(\"/:storeId/settings\", async (req: Request, res: Response) => {\n  const { storeId } = req.params;\n  // Store loyalty settings in store metadata\n  res.json({ success:true, message:\"Loyalty settings saved\", data:req.body });\n});\nrouter.get(\"/status\", async (req: Request, res: Response) => {\n  try {\n    const { customerId, storeId } = req.query as { customerId: string; storeId: string };\n    const data = await getLoyaltyStatus(customerId, storeId);\n    res.json({ success: true, data });\n  } catch (err: any) { res.status(500).json({ success: false, message: err.message }); }\n});\n\n// POST /api/loyalty/award (called internally after order paid)\nrouter.post(\"/award\", async (req: Request, res: Response) => {\n  try {\n    const { orderId } = req.body;\n    await awardPoints(orderId);\n    res.json({ success: true });\n  } catch (err: any) { res.status(500).json({ success: false, message: err.message }); }\n});\n\n// POST /api/loyalty/redeem\nrouter.post(\"/redeem\", async (req: Request, res: Response) => {\n  try {\n    const { customerId, storeId, pointsToRedeem, orderId } = req.body;\n    const result = await redeemPoints({ customerId, storeId, pointsToRedeem: Number(pointsToRedeem), orderId });\n    res.json({ success: true, data: result });\n  } catch (err: any) { res.status(500).json({ success: false, message: err.message }); }\n});\n\nexport default router;\n"};
for(const [rel,content] of Object.entries(files)){
  const p=rel.replace(/\//g,path.sep);
  fs.mkdirSync(path.dirname(p),{recursive:true});
  fs.writeFileSync(p,content,'utf8');
}
execSync('git add .',{stdio:'inherit'});
execSync('git commit -m "fix: loyalty reduce typed initial value TS2345"',{stdio:'inherit'});
execSync('git push origin main',{stdio:'inherit'});
console.log('Pushed.');